CREATE TABLE mitarbeiter (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  vorname VARCHAR(255) NOT NULL,
  wohnort VARCHAR(255) NOT NULL,
  adresse VARCHAR(255) NOT NULL,
  geburtstag DATE NOT NULL
);

CREATE TABLE kunde (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  vorname VARCHAR(255) NOT NULL,
  wohnort VARCHAR(255) NOT NULL,
  adresse VARCHAR(255) NOT NULL,
  foto TEXT NOT NULL
);

CREATE TABLE standorte (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  strasse VARCHAR(255) NOT NULL,
  ort VARCHAR(255) NOT NULL,
  plz VARCHAR(255) NOT NULL,
  telefon_nr VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  standort_name VARCHAR(255) NOT NULL
);

CREATE TABLE kunden_pro_standort (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  kunde_id INTEGER NOT NULL,
  standort_id INTEGER NOT NULL
);

CREATE TABLE mitarbeiter_pro_standort (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  mitarbieter_id INTEGER NOT NULL,
  standort_id INTEGER NOT NULL
);

CREATE TABLE abo_modell (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  abo_dauer INTEGER NOT NULL,
  kosten FLOAT(25) NOT NULL,
  abo_name VARCHAR(255) NOT NULL
);

CREATE TABLE abo_kaufhistorie (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  kunde_id INTEGER NOT NULL,
  abo_medell_id INTEGER NOT NULL,
  abo_anfang DATE NOT NULL,
  abo_ende DATE NOT NULL,
  kuendigung DATE
);
